# Generated by Django 4.2.28 on 2026-03-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentrecord",
            old_name="razorpay_order_id",
            new_name="reference_id",
        ),
        migrations.RemoveField(
            model_name="paymentrecord",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="paymentrecord",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="paymentrecord",
            name="razorpay_signature",
        ),
        migrations.RemoveField(
            model_name="paymentrecord",
            name="status",
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Verification"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("free", "Free"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="screenshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="payment_screenshots/"
            ),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
