# Generated by Django 5.2.12 on 2026-03-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referral_code", models.CharField(max_length=50, unique=True)),
                ("ambassador_name", models.CharField(max_length=255)),
                ("ambassador_email", models.EmailField(max_length=254)),
                (
                    "discount_percentage",
                    models.PositiveIntegerField(
                        help_text="Discount percentage (0-100)"
                    ),
                ),
                (
                    "max_usage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of times this code can be used",
                        null=True,
                    ),
                ),
                ("current_usage", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
