# Generated by Django 4.2.28 on 2026-03-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userregistration",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="userregistration",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="userregistration",
            name="razorpay_signature",
        ),
        migrations.AddField(
            model_name="userregistration",
            name="reference_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Payment Reference ID",
            ),
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Verification"),
                    ("VERIFIED", "Verified"),
                    ("REJECTED", "Rejected"),
                    ("FREE", "Free"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
