# Generated by Django 4.2.28 on 2026-03-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0002_remove_userregistration_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userregistration",
            name="registration_type",
            field=models.CharField(
                choices=[
                    ("PARTICIPANT", "Participant"),
                    ("EXHIBITOR", "Exhibitor"),
                    ("VISITOR", "Visitor"),
                ],
                max_length=20,
            ),
        ),
    ]
