# Generated by Django 4.2.28 on 2026-03-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0003_alter_userregistration_registration_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregistration",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, help_text="Chronological age", null=True
            ),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="city",
            field=models.CharField(
                blank=True, help_text="City of residence", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                help_text="Gender identity",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="college",
            field=models.CharField(
                blank=True,
                help_text="Institutional affiliation / Organisation",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Brief technical or business core",
                null=True,
                verbose_name="Product/Startup Description",
            ),
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="email",
            field=models.EmailField(
                help_text="Official communication node", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="name",
            field=models.CharField(
                help_text="Full legal name as per ID", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="org_name",
            field=models.CharField(
                blank=True,
                help_text="Venture or entity designation",
                max_length=255,
                null=True,
                verbose_name="Organization/Startup Name",
            ),
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="phone",
            field=models.CharField(help_text="Active contact sequence", max_length=20),
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Digital archive or portfolio",
                null=True,
                verbose_name="Website/Social Media Link",
            ),
        ),
    ]
