# Generated by Django 4.2.28 on 2026-03-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0004_userregistration_age_userregistration_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregistration",
            name="exhibitor_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXHIBITION", "Exhibition Partner"),
                    ("WORKSHOP", "Workshop Partner"),
                    ("MERCHANDISED", "Merchandised Partner"),
                    ("MEDIA", "Media Partner"),
                ],
                help_text="Category of exhibition partnership",
                max_length=50,
                null=True,
            ),
        ),
    ]
