# Generated by Django 4.2.28 on 2026-03-07 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registrations", "0005_userregistration_exhibitor_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregistration",
            name="round1_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="round2_unlocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="selected_for_round2",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
