# Generated by Django 4.2.28 on 2026-03-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0006_userregistration_round1_completed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeEntryWhitelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="The domain or email to whitelist",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "whitelist_type",
                    models.CharField(
                        choices=[
                            ("DOMAIN", "Email Domain (e.g., gmail.com)"),
                            ("EMAIL", "Specific Email Address"),
                        ],
                        default="DOMAIN",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Reason or note for this whitelist entry",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Free Entry Whitelist",
            },
        ),
    ]
