# Generated by Django 4.2.28 on 2026-03-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0008_attendancesession_attendancerecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(default="Ennovate'X-26", max_length=255),
                ),
                ("is_registration_open", models.BooleanField(default=True)),
                ("round1_name", models.CharField(default="Round 1", max_length=100)),
                ("round2_name", models.CharField(default="Round 2", max_length=100)),
                (
                    "contact_email",
                    models.EmailField(default="nexus@ecellpccoe.com", max_length=254),
                ),
            ],
            options={
                "verbose_name": "Event Settings",
                "verbose_name_plural": "Event Settings",
            },
        ),
    ]
