# Generated by Django 4.2.28 on 2026-03-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0009_eventsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregistration",
            name="idea_agreement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="idea_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="idea_domain",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="idea_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="round1_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="round2_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="round3_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="round3_unlocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="selected_for_round3",
            field=models.BooleanField(default=False),
        ),
    ]
