# Generated by Django 5.2.12 on 2026-03-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0010_userregistration_idea_agreement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregistration",
            name="registration_email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="round2_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
