# Generated by Django 6.0.3 on 2026-03-16 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_userregistration_registration_email_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundTimingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_formation_start', models.DateTimeField(blank=True, null=True)),
                ('team_formation_end', models.DateTimeField(blank=True, null=True)),
                ('ppt_submission_start', models.DateTimeField(blank=True, null=True)),
                ('ppt_submission_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Round Timing Setting',
                'verbose_name_plural': 'Round Timing Settings',
            },
        ),
        migrations.CreateModel(
            name='RoundNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ROUND2_SELECTED', 'Round 2 Shortlisted'), ('ROUND2_NOT_SELECTED', 'Round 2 Not Shortlisted'), ('ROUND3_SELECTED', 'Round 3 Shortlisted')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='registrations.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('team_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed')], default='DRAFT', max_length=20)),
                ('selected_for_round3', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to='registrations.userregistration')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Round3Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt_file', models.FileField(upload_to='round3_submissions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.userregistration')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='round3_submission', to='registrations.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_membership', to='registrations.userregistration')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='registrations.team')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
