# Generated by Django 6.0.3 on 2026-03-14 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_team_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='selected_for_round3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Round3Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt_file', models.FileField(upload_to='round3_submissions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='round3_submission', to='registrations.team')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='RoundNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ROUND2_SELECTED', 'Round 2 Shortlisted'), ('ROUND2_NOT_SELECTED', 'Round 2 Not Shortlisted'), ('ROUND3_SELECTED', 'Round 3 Shortlisted')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='registrations.userregistration')),
            ],
        ),
    ]
