# Generated by Django 6.0.3 on 2026-03-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_team_selected_for_round3_team_team_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundTimingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_formation_start', models.DateTimeField(blank=True, null=True)),
                ('team_formation_end', models.DateTimeField(blank=True, null=True)),
                ('ppt_submission_start', models.DateTimeField(blank=True, null=True)),
                ('ppt_submission_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Round Timing Setting',
                'verbose_name_plural': 'Round Timing Settings',
            },
        ),
    ]
